<a href="https://colab.research.google.com/github/TiredRebel/Math_hw_1/blob/main/1_Images_as_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Задача 1. Робота з зображеннями як з матрицями (аналітичні обчислення)

**Коментар:** Цифрове зображення можна розглядати як матрицю яскравостей пікселів. Операції редагування — це арифметика над матрицями.

### Дано

$$
M=
\begin{pmatrix}
100 & 150 & 200\\
50 & 100 & 150\\
0 & 50 & 100
\end{pmatrix},
\qquad
E=
\begin{pmatrix}
20 & 30 & 40\\
10 & 20 & 30\\
5 & 10 & 15
\end{pmatrix}
$$

---

## 1) Зміна контрасту (зменшення яскравості)

**Коментар:** Множимо матрицю $M$ на скаляр $0.5$. Це означає, що **кожен елемент** матриці множиться на $0.5$.

$$
0.5M=
\begin{pmatrix}
0.5\cdot100 & 0.5\cdot150 & 0.5\cdot200\\
0.5\cdot50  & 0.5\cdot100 & 0.5\cdot150\\
0.5\cdot0   & 0.5\cdot50  & 0.5\cdot100
\end{pmatrix}
$$

**Проміжні обчислення:**

$$
0.5\cdot100=50,\quad 0.5\cdot150=75,\quad 0.5\cdot200=100
$$

$$
0.5\cdot50=25,\quad 0.5\cdot0=0
$$

**Результат:**

$$
0.5M=
\begin{pmatrix}
50 & 75 & 100\\
25 & 50 & 75\\
0  & 25 & 50
\end{pmatrix}
$$

---

## 2) Корекція яскравості

**Коментар:** Додаємо скаляр $25$ до матриці $M$. Це означає, що **до кожного елемента** матриці додаємо 25.

$$
M+25=
\begin{pmatrix}
100+25 & 150+25 & 200+25\\
50+25  & 100+25 & 150+25\\
0+25   & 50+25  & 100+25
\end{pmatrix}
$$

**Проміжні обчислення:**

$$
100+25=125,\quad 150+25=175,\quad 200+25=225
$$

$$
50+25=75,\quad 0+25=25
$$

**Результат:**

$$
M+25=
\begin{pmatrix}
125 & 175 & 225\\
75  & 125 & 175\\
25  & 75  & 125
\end{pmatrix}
$$

---

## 3) Змішування (Blending)

**Коментар:** Створюємо нове зображення як лінійну комбінацію: беремо $80\%$ від $M$ і додаємо $20\%$ від $E$.
Зручно спочатку окремо обчислити $0.8M$ та $0.2E$, а потім скласти.

### Крок 1. Обчислюємо $0.8M$

$$
0.8M=
\begin{pmatrix}
0.8\cdot100 & 0.8\cdot150 & 0.8\cdot200\\
0.8\cdot50  & 0.8\cdot100 & 0.8\cdot150\\
0.8\cdot0   & 0.8\cdot50  & 0.8\cdot100
\end{pmatrix}
=
\begin{pmatrix}
80 & 120 & 160\\
40 & 80  & 120\\
0  & 40  & 80
\end{pmatrix}
$$

### Крок 2. Обчислюємо $0.2E$

$$
0.2E=
\begin{pmatrix}
0.2\cdot20 & 0.2\cdot30 & 0.2\cdot40\\
0.2\cdot10 & 0.2\cdot20 & 0.2\cdot30\\
0.2\cdot5  & 0.2\cdot10 & 0.2\cdot15
\end{pmatrix}
=
\begin{pmatrix}
4 & 6 & 8\\
2 & 4 & 6\\
1 & 2 & 3
\end{pmatrix}
$$

### Крок 3. Додаємо: $0.8M+0.2E$

**Коментар:** Додаємо матриці поелементно (кожен піксель — це сума відповідних елементів).

$$
0.8M+0.2E=
\begin{pmatrix}
80+4 & 120+6 & 160+8\\
40+2 & 80+4  & 120+6\\
0+1  & 40+2  & 80+3
\end{pmatrix}
$$

**Проміжні обчислення поелементно:**

$$
80+4=84,\quad 120+6=126,\quad 160+8=168
$$

$$
40+2=42,\quad 80+4=84,\quad 120+6=126
$$

$$
0+1=1,\quad 40+2=42,\quad 80+3=83
$$

**Результат:**

$$
0.8M+0.2E=
\begin{pmatrix}
84 & 126 & 168\\
42 & 84  & 126\\
1  & 42  & 83
\end{pmatrix}
$$



In [1]:
import numpy as np

M = np.array([
    [100, 150, 200],
    [ 50, 100, 150],
    [  0,  50, 100]
], dtype=float)

E = np.array([
    [20, 30, 40],
    [10, 20, 30],
    [ 5, 10, 15]
], dtype=float)

# 1) Контраст (зменшення яскравості)
contrast = 0.5 * M

# 2) Яскравість +25
brightness = M + 25

# 3) Blending
blend = 0.8 * M + 0.2 * E

print("M:\n", M)
print("\nE:\n", E)

print("\n1) 0.5 * M (contrast):\n", contrast)
print("\n2) M + 25 (brightness):\n", brightness)
print("\n3) 0.8*M + 0.2*E (blend):\n", blend)


M:
 [[100. 150. 200.]
 [ 50. 100. 150.]
 [  0.  50. 100.]]

E:
 [[20. 30. 40.]
 [10. 20. 30.]
 [ 5. 10. 15.]]

1) 0.5 * M (contrast):
 [[ 50.  75. 100.]
 [ 25.  50.  75.]
 [  0.  25.  50.]]

2) M + 25 (brightness):
 [[125. 175. 225.]
 [ 75. 125. 175.]
 [ 25.  75. 125.]]

3) 0.8*M + 0.2*E (blend):
 [[ 84. 126. 168.]
 [ 42.  84. 126.]
 [  1.  42.  83.]]
